// Copyright (c) 2020, 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
* @addtogroup CVMDeviceUniqueKey
* @{
  Class CVMDeviceUniqueKey implements \link IVMDeviceUniqueKey \endlink interface.
	
  The class ID `VMDeviceUniqueKey` is not included in the default privilege set.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CVMDeviceUniqueKey_UID UINT32_C(345)
