// Copyright (c) 2020, 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/** @file  IVMDeviceUniqueKey.idl */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IVMDeviceUniqueKey_OP_derive 0

static inline int32_t
IVMDeviceUniqueKey_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IVMDeviceUniqueKey_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IVMDeviceUniqueKey_derive(Object self, void *outKey_ptr, size_t outKey_len, size_t *outKey_lenout)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { outKey_ptr, outKey_len * 1 };

  int32_t result = Object_invoke(self, IVMDeviceUniqueKey_OP_derive, a, ObjectCounts_pack(0, 1, 0, 0));

  *outKey_lenout = a[0].b.size / 1;

  return result;
}

