ifeq ($(TARGET_BOARD_PLATFORM),sun)
ENABLE_SECCAM_2_0 := true
ENABLE_SECCAM_2_0_AIDL := true

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_TRUSTED_UI_2_0 := false
ENABLE_TRUSTED_UI_VM_3_0 := true
ENABLE_TRUSTED_UI_LISTENER := true
ENABLE_TRUSTED_UI_AIDL := true
ENABLE_HDCPCAPABILITY_OPTIMIZATION := true
ENABLE_PERIPHERAL_STATE_UTILS := true
ENABLE_HLOS_DATA_PATH := true
ENABLE_HDCP_DP := true
ENABLE_HDCP_USING_SMCINVOKE := true

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),neo61)
ENABLE_OPS_LISTENER := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),blair)
ENABLE_SECCAM_2_0 := true
ENABLE_SECCAM_2_0_AIDL := true
DISABLE_CSF_VERSION_CHECK := true

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_AIDL := true
ENABLE_TRUSTED_UI_VM_3_0 := false
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
ENABLE_HDCPCAPABILITY_OPTIMIZATION := false
ENABLE_PERIPHERAL_STATE_UTILS := false
ENABLE_HLOS_DATA_PATH := false

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),pineapple)
ENABLE_SECCAM_2_0 := true
ENABLE_SECCAM_2_0_AIDL := true
DISABLE_CSF_VERSION_CHECK := false

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_VM_3_0 := true
ENABLE_TRUSTED_UI_AIDL := true
ENABLE_HDCPCAPABILITY_OPTIMIZATION := true
ENABLE_PERIPHERAL_STATE_UTILS := true
ENABLE_HLOS_DATA_PATH := true
ENABLE_HDCP_DP := true
ENABLE_HDCP_USING_SMCINVOKE := true

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),anorak61)
ENABLE_SECCAM_2_0 := true
ENABLE_SECCAM_2_0_AIDL := true
DISABLE_CSF_VERSION_CHECK := false

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_HDCPCAPABILITY_OPTIMIZATION := false
ENABLE_HLOS_DATA_PATH := false

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),volcano)
ENABLE_SECCAM_2_0 := true
ENABLE_SECCAM_2_0_AIDL := true
DISABLE_CSF_VERSION_CHECK := false

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_VM_3_0 := true
ENABLE_TRUSTED_UI_LISTENER := true
ENABLE_TRUSTED_UI_AIDL := true
ENABLE_HDCPCAPABILITY_OPTIMIZATION := true
ENABLE_PERIPHERAL_STATE_UTILS := false
ENABLE_HLOS_DATA_PATH := true
ENABLE_HDCP_DP := true
ENABLE_HDCP_USING_SMCINVOKE := true

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),niobe)
ENABLE_SECCAM_2_0 := true
ENABLE_SECCAM_2_0_AIDL := true

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_TRUSTED_UI_2_0 := false
ENABLE_TRUSTED_UI_VM_3_0 := false
ENABLE_TRUSTED_UI_LISTENER := false
ENABLE_TRUSTED_UI_AIDL := false
ENABLE_HDCPCAPABILITY_OPTIMIZATION := true
ENABLE_PERIPHERAL_STATE_UTILS := false
ENABLE_HLOS_DATA_PATH := true
ENABLE_HDCP_DP := true
ENABLE_HDCP_USING_SMCINVOKE := true

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),kalama)
ENABLE_SECCAM_2_0 := true

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_VM_3_0 := true
ENABLE_TRUSTED_UI_LISTENER := true
ENABLE_HDCPCAPABILITY_OPTIMIZATION := true
ENABLE_PERIPHERAL_STATE_UTILS := true
ENABLE_HLOS_DATA_PATH := true
ENABLE_HDCP_DP := true

#FSP definitions
ENABLE_FSP  := true
DISABLE_FSP_LICENSE_CHECK := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),monaco)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),taro)
ENABLE_SECCAM_2_0 := true

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_VM_3_0 := true
ENABLE_FSP  := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),holi)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),lahaina)
ENABLE_SECCAM_2_0 := true
ENABLE_TRUSTED_UI_2_0 := true
ENABLE_TRUSTED_UI_VM_3_0 := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_WIDEVINE_LOAD_LICENSE := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),kona)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_OPS_SYSFS := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),lito)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK
APP_BUFFER_CFLAGS := -DAPP_BUF_ALIGNMENT=0x1000

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),bengal)
ifeq ($(TARGET_BOARD_SUFFIX),_515)
ENABLE_SECCAM_2_0 := true
ENABLE_TRUSTED_UI_2_0 := true
else
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
endif
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ifeq ($(TARGET_BOARD_PLATFORM),bengal_32)
ENABLE_WIDEVINE_OEMCRYPTO := false
else
ENABLE_WIDEVINE_OEMCRYPTO := true
endif
WIDEVINE_USES_SMCINVOKE := true
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),atoll)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := true
TARGET_SUPPORTS_QCE_MAPPING := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),gen4)
ENABLE_SECCAM := false
ENABLE_SECCAM_QTI_SERVICE := false
ENABLE_SECURE_UI := false
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true

#Playready DRM definitions
ifeq ($(TARGET_BOARD_AUTO),true)
ENABLE_PLAYREADY_DRM := true
ENABLE_PLAYREADY_AIDL_SERVICE := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := true
PLAYREADY_SUPPORTS_LAT := false
endif
endif

ifeq ($(TARGET_BOARD_PLATFORM),msmnile)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true

#Playready DRM definitions
ifeq ($(TARGET_BOARD_AUTO),true)
ENABLE_PLAYREADY_DRM := true
ENABLE_PLAYREADY_AIDL_SERVICE := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := true
PLAYREADY_SUPPORTS_LAT := false
endif
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdmshrike)
ENABLE_SECCAM := true
ENABLE_SECCAM_QTI_SERVICE := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := true
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true

#Playready DRM definitions
ifeq ($(TARGET_BOARD_AUTO),true)
ENABLE_PLAYREADY_DRM := true
ENABLE_PLAYREADY_AIDL_SERVICE := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := true
PLAYREADY_SUPPORTS_LAT := false
endif
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm845)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),$(TRINKET))
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),$(MSMSTEPPE))
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#Widevine DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true

#Playready DRM definitions
ifeq ($(TARGET_BOARD_AUTO),true)
ENABLE_PLAYREADY_DRM := true
ENABLE_PLAYREADY_AIDL_SERVICE := true
PLAYREADY_USES_CP_ION_V2 := true
PLAYREADY_SUPPORTS_OPS := false
PLAYREADY_SUPPORTS_LAT := false
endif
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm710)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_WIDEVINE_OEMCRYPTO := true
WIDEVINE_USES_SMCINVOKE := false
WIDEVINE_USES_CE_SMMU := false
ENABLE_OPS_LISTENER := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
DISABLE_DISPLAY_CLK_VOTING := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),sdm660)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_TS_LOOPBACK

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8998)
ENABLE_SECCAM := true
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8998

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8996)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8996

#DRM definitions
ENABLE_WIDEVINE_DRM := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8937)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_THORIUM

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msm8953)
ENABLE_SECURE_UI := true
ST_TARGET_CFLAGS := -DST_TARGET_MSM8953

#DRM definitions
ENABLE_WIDEVINE_DRM := true
ENABLE_TRUSTED_APP_LOADER := true
TARGET_ENABLE_MEDIADRM_64 := true
OTA_FLAG_FOR_DRM := true
ENABLE_HDCP_DP := true
endif

#Disable widevine L1 support for GO targets
ifeq ($(TARGET_BOARD_SUFFIX),_32go)
ENABLE_WIDEVINE_OEMCRYPTO := false
endif

# TUI and SECCAM will not be supported on LOW RAM chipsets
ifeq ($(TARGET_HAS_LOW_RAM),true)
ENABLE_TRUSTED_UI_2_0 := false
ENABLE_TRUSTED_UI_VM_3_0 := false
ENABLE_TRUSTED_UI_LISTENER := false
ENABLE_TRUSTED_UI_AIDL := false
ENABLE_SECCAM_2_0 := false
ENABLE_SECCAM_2_0_AIDL := false
endif

ifeq ($(TARGET_USES_QMAA),true)
ifneq ($(TARGET_USES_QMAA_OVERRIDE_DRM),true)
ENABLE_TRUSTED_UI_2_0 := false
ENABLE_TRUSTED_UI_VM_3_0 := false
ENABLE_TRUSTED_UI_LISTENER := false
endif
endif
