ifeq ($(TARGET_BOARD_PLATFORM),blair)
SSGTZD_DAEMON := true
SSGTZD_VENDOR_CLIENTS := true
TARGET_ENABLE_SAVE_QTEEDIAG := false
TARGET_ENABLE_TAAUTO_LOAD   := false
TARGET_ENABLE_TUNNEL_INVOKE   := false
ENABLE_SSGTZD_VM_SERVICES   := true
ENABLE_SSGTZD_MODEM_SERVICE := false
endif

ifeq ($(TARGET_BOARD_PLATFORM),pineapple)
SSGTZD_DAEMON := true
SSGTZD_VENDOR_CLIENTS := true
TARGET_ENABLE_SAVE_QTEEDIAG := false
TARGET_ENABLE_TAAUTO_LOAD   := true
TARGET_ENABLE_TUNNEL_INVOKE := true
ENABLE_SSGTZD_VM_SERVICES   := true
ENABLE_SSGTZD_MODEM_SERVICE := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),volcano)
SSGTZD_DAEMON := true
SSGTZD_VENDOR_CLIENTS := true
TARGET_ENABLE_SAVE_QTEEDIAG := false
TARGET_ENABLE_TAAUTO_LOAD   := true
TARGET_ENABLE_TUNNEL_INVOKE := true
ENABLE_SSGTZD_VM_SERVICES   := true
ENABLE_SSGTZD_MODEM_SERVICE := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),sun)
SSGTZD_DAEMON := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),msmnile)
SSGTZD_DAEMON := true
TARGET_ENABLE_TAAUTO_LOAD   := true
endif

ifeq ($(TARGET_BOARD_PLATFORM),anorak61)
SSGTZD_DAEMON := true
SSGTZD_VENDOR_CLIENTS := true
TARGET_ENABLE_SAVE_QTEEDIAG := false
TARGET_ENABLE_TAAUTO_LOAD   := false
TARGET_ENABLE_TUNNEL_INVOKE   := false
ENABLE_SSGTZD_VM_SERVICES   := false
ENABLE_SSGTZD_MODEM_SERVICE := false
endif
