// Copyright (c) 2021 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
* @addtogroup CQTEEEnvInfo
* @{
  Class CQTEEEnvInfo implements \link IQTEEEnvInfo \endlink interface.
*/
// This class exposes methods to gather environment information from QTEE.
//
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CQTEEEnvInfo_UID UINT32_C(29)

