// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CRPMBService
* @{
  Class CRPMBService implements \link IRPMBService \endlink interface.

*/
// This class provides an interface to access legacy QSEECOM services via SMCI.
//
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CRPMBService_UID UINT32_C(274)


