/*===================================================================================
    Copyright (c) 2020-2021 Qualcomm Technologies, Inc.
    All Rights Reserved.
    Confidential and Proprietary - Qualcomm Technologies, Inc.
 ===================================================================================*/
/** @file ICPZLicense.idl */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define ICPZLicense_FEATURE_ID_CPZ UINT32_C(1)
#define ICPZLicense_FEATURE_ID_WIDEVINE UINT32_C(2)
#define ICPZLicense_FEATURE_ID_FSP UINT32_C(3)

#define ICPZLicense_ERROR_BUSY_TRY_AGAIN INT32_C(10)
#define ICPZLicense_ERROR_FAILED_TO_CHECK_LICENSE INT32_C(11)
#define ICPZLicense_ERROR_FAILED_TO_GET_LICENSE INT32_C(12)
#define ICPZLicense_ERROR_FAILED_TO_VERIFY_LICENSE INT32_C(13)

#define ICPZLicense_OP_check 0

static inline int32_t
ICPZLicense_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ICPZLicense_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ICPZLicense_check(Object self, uint32_t featureID_val)
{
  ObjectArg a[1];
  a[0].b = (ObjectBuf) { &featureID_val, sizeof(uint32_t) };

  return Object_invoke(self, ICPZLicense_OP_check, a, ObjectCounts_pack(1, 0, 0, 0));
}
