// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
 * Describes the interface for memory objects.
 *
 * This interface is identical to the generic interface (no added methods),
 * but allows other interfaces which reference shareable memory objects to
 * specify that the object in question is expected to be a memory object.
 */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"


static inline int32_t
IMemObject_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IMemObject_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}



