// Copyright (c) 2015, 2021 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
// IModule.idl
//
// This interface requests objects from modules.
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IModule.h"

#define IModule_DEFINE_INVOKE(func, prefix, type) \
  int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
  { \
    type me = (type) h; \
    switch (ObjectOp_methodID(op)) { \
      case Object_OP_release: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##release(me); \
      } \
      case Object_OP_retain: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##retain(me); \
      } \
      case IModule_OP_open: { \
        if (k != ObjectCounts_pack(1, 0, 1, 1) || \
          a[0].b.size != 4) { \
          break; \
        } \
        const uint32_t *id_ptr = (const uint32_t*) a[0].b.ptr; \
        return prefix##open(me, *id_ptr, a[1].o, &a[2].o); \
      } \
      case IModule_OP_shutdown: { \
        if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
          break; \
        } \
        return prefix##shutdown(me); \
      } \
    } \
    return Object_ERROR_INVALID; \
  }


