#pragma once
// Copyright (c) 2015, 2021 Qualcomm Technologies, Inc.

// All Rights Reserved.

// Confidential and Proprietary - Qualcomm Technologies, Inc.

// IModule.idl

//

// This interface requests objects from modules.

/** @cond */

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"
#include "impl_base.hpp"
#include "IModule.hpp"

class IModuleImplBase : protected ImplBase, public IIModule {
   public:
    IModuleImplBase() {}
    virtual ~IModuleImplBase() {}

   protected:
    virtual int32_t invoke(ObjectOp op, ObjectArg* a, ObjectCounts k) {
        switch (ObjectOp_methodID(op)) {
            case OP_open: {
                if (k != ObjectCounts_pack(1, 0, 1, 1) ||
                    a[0].b.size != 4) {
                    break;
                }
                const uint32_t* id_ptr = (const uint32_t*)a[0].b.ptr;
                ProxyBase p_credentials(a[1].o);
                ProxyBase p_obj;
                int32_t r = open(*id_ptr, p_credentials, p_obj);
                p_credentials.extract();
                a[2].o = p_obj.extract();
                return r;
            }
            case OP_shutdown: {
                if (k != ObjectCounts_pack(0, 0, 0, 0)) {
                    break;
                }
                return shutdown();
            }
            default: { return Object_ERROR_INVALID; }
        }
        return Object_ERROR_INVALID;
    }
};

