/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All rights reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
/**
 * @section IPFMCallback_Overview
 * IPFMCallback is the interface for client to create callback object
 * to get notified when there are changes to the status of registered FIDs.
 */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IPFMCallback_OP_Notify 0

static inline int32_t
IPFMCallback_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IPFMCallback_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IPFMCallback_Notify(Object self, const void *info_ptr, size_t info_len)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].bi = (ObjectBufIn) { info_ptr, info_len * 1 };

  return Object_invoke(self, IPFMCallback_OP_Notify, a, ObjectCounts_pack(1, 0, 0, 0));
}
