#pragma once
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All rights reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */

/**
 * @section IPFMCallback_Overview
 * IPFMCallback is the interface for client to create callback object
 * to get notified when there are changes to the status of registered FIDs.
 */

/** @cond */

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

class IIPFMCallback {
   public:
    virtual ~IIPFMCallback() {}

    virtual int32_t Notify(const void* info_ptr, size_t info_len) = 0;

   protected:
    static const ObjectOp OP_Notify = 0;
};

class IPFMCallback : public IIPFMCallback, public ProxyBase {
   public:
    IPFMCallback() {}
    IPFMCallback(Object impl) : ProxyBase(impl) {}
    virtual ~IPFMCallback() {}

    virtual int32_t Notify(const void* info_ptr, size_t info_len) {
        ObjectArg a[1]={{{0,0}}};
        a[0].bi = (ObjectBufIn) {info_ptr, info_len * 1};

        return invoke(OP_Notify, a, ObjectCounts_pack(1, 0, 0, 0));
    }

};

