#pragma once
// Copyright (c) 2021 Qualcomm Technologies, Inc.

// All Rights Reserved.

// Confidential and Proprietary - Qualcomm Technologies, Inc.

/** @cond */

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

class IIQTEEEnvInfo {
   public:
    static const uint32_t SUPPORTS_32_BIT = UINT32_C(1);
    static const uint32_t SUPPORTS_64_BIT = UINT32_C(2);

    virtual ~IIQTEEEnvInfo() {}

    virtual int32_t getSupportedArchitectures(uint8_t* architecturesSupported_ptr) = 0;

   protected:
    static const ObjectOp OP_getSupportedArchitectures = 0;
};

class IQTEEEnvInfo : public IIQTEEEnvInfo, public ProxyBase {
   public:
    IQTEEEnvInfo() {}
    IQTEEEnvInfo(Object impl) : ProxyBase(impl) {}
    virtual ~IQTEEEnvInfo() {}

    virtual int32_t getSupportedArchitectures(uint8_t* architecturesSupported_ptr) {
        ObjectArg a[1]={{{0,0}}};
        a[0].b = (ObjectBuf) {architecturesSupported_ptr, sizeof(uint8_t)};

        return invoke(OP_getSupportedArchitectures, a, ObjectCounts_pack(0, 1, 0, 0));
    }

};

