// Copyright (c) 2021 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IQTEEEnvInfo_SUPPORTS_32_BIT UINT32_C(1)
#define IQTEEEnvInfo_SUPPORTS_64_BIT UINT32_C(2)

#define IQTEEEnvInfo_OP_getSupportedArchitectures 0

static inline int32_t
IQTEEEnvInfo_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IQTEEEnvInfo_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IQTEEEnvInfo_getSupportedArchitectures(Object self, uint8_t *architecturesSupported_ptr)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].b = (ObjectBuf) { architecturesSupported_ptr, sizeof(uint8_t) };

  return Object_invoke(self, IQTEEEnvInfo_OP_getSupportedArchitectures, a, ObjectCounts_pack(0, 1, 0, 0));
}

