/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 * All rights reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
/** @file IQWESConfig.idl */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IQWESConfig_OPT_SELECT_TEST_ROOT UINT64_C(0x00000001)
#define IQWESConfig_CLOUD_TTIME UINT32_C(1)
#define IQWESConfig_SET_TIME_TO_LIVE UINT32_C(2)

#define IQWESConfig_ERROR_OPTS_NOT_SUPPORTED INT32_C(10)
#define IQWESConfig_ERROR_INVALID_PARAM INT32_C(11)
#define IQWESConfig_ERROR_TTIME_ALREADY_SET INT32_C(12)
#define IQWESConfig_ERROR_INVALID_NONCE INT32_C(13)
#define IQWESConfig_ERROR_REQUEST_EXPIRED INT32_C(14)
#define IQWESConfig_ERROR_ECDSA_VERIFY_SIGNATURE INT32_C(15)
#define IQWESConfig_ERROR_CBOR_INVALID_BUFFER_SIZE INT32_C(16)
#define IQWESConfig_ERROR_CBOR_DECODE_FAILED INT32_C(17)
#define IQWESConfig_ERROR_CBOR_ENCODE_FAILED INT32_C(18)
#define IQWESConfig_ERROR_PACKET_FORMAT INT32_C(19)
#define IQWESConfig_ERROR_INVALID_PROPERTY_ID INT32_C(20)

#define IQWESConfig_OP_getNonce 0
#define IQWESConfig_OP_setProperty 1
#define IQWESConfig_OP_setOptions 2

static inline int32_t
IQWESConfig_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IQWESConfig_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IQWESConfig_getNonce(Object self, void *nonce_ptr, size_t nonce_len, size_t *nonce_lenout)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].b = (ObjectBuf) { nonce_ptr, nonce_len * 1 };

  int32_t result = Object_invoke(self, IQWESConfig_OP_getNonce, a, ObjectCounts_pack(0, 1, 0, 0));

  *nonce_lenout = a[0].b.size / 1;

  return result;
}

static inline int32_t
IQWESConfig_setProperty(Object self, uint32_t propertyID_val, const void *propertyValue_ptr, size_t propertyValue_len)
{
  ObjectArg a[2]={{{0,0}}};
  a[0].b = (ObjectBuf) { &propertyID_val, sizeof(uint32_t) };
  a[1].bi = (ObjectBufIn) { propertyValue_ptr, propertyValue_len * 1 };

  return Object_invoke(self, IQWESConfig_OP_setProperty, a, ObjectCounts_pack(2, 0, 0, 0));
}

static inline int32_t
IQWESConfig_setOptions(Object self, uint64_t optionValue_val)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].b = (ObjectBuf) { &optionValue_val, sizeof(uint64_t) };

  return Object_invoke(self, IQWESConfig_OP_setOptions, a, ObjectCounts_pack(1, 0, 0, 0));
}



