/********************************************************************
Copyright (c) 2020 Qualcomm Technologies, Inc.
All Rights Reserved.
Confidential and Proprietary - Qualcomm Technologies, Inc.
*********************************************************************/

#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define IRegisterApp_OP_registerApp 0
#define IRegisterApp_OP_deregisterApp 1

static inline int32_t
IRegisterApp_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
IRegisterApp_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
IRegisterApp_registerApp(Object self, uint32_t uid_val, Object callback_val, const uint8_t *secret_ptr, size_t secret_len)
{
  ObjectArg a[3];
  a[0].b = (ObjectBuf) { &uid_val, sizeof(uint32_t) };
  a[2].o = callback_val;
  a[1].bi = (ObjectBufIn) { secret_ptr, secret_len * sizeof(uint8_t) };

  return Object_invoke(self, IRegisterApp_OP_registerApp, a, ObjectCounts_pack(2, 0, 1, 0));
}

static inline int32_t
IRegisterApp_deregisterApp(Object self, uint32_t uid_val, const uint8_t *secret_ptr, size_t secret_len)
{
  ObjectArg a[2];
  a[0].b = (ObjectBuf) { &uid_val, sizeof(uint32_t) };
  a[1].bi = (ObjectBufIn) { secret_ptr, secret_len * sizeof(uint8_t) };

  return Object_invoke(self, IRegisterApp_OP_deregisterApp, a, ObjectCounts_pack(2, 0, 0, 0));
}



