/* Copyright (c) 2019-2020,2023 Qualcomm Technologies, Inc.
   All Rights Reserved.
   Confidential and Proprietary - Qualcomm Technologies, Inc. */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define ISecureCamera2Notify_EVENT_PROTECTED UINT32_C(1)
#define ISecureCamera2Notify_EVENT_UNPROTECTED UINT32_C(2)

#define ISecureCamera2Notify_OP_event 0

static inline int32_t
ISecureCamera2Notify_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
ISecureCamera2Notify_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
ISecureCamera2Notify_event(Object self, uint32_t state_val)
{
  ObjectArg a[1]={{{0,0}}};
  a[0].b = (ObjectBuf) { &state_val, sizeof(uint32_t) };

  return Object_invoke(self, ISecureCamera2Notify_OP_event, a, ObjectCounts_pack(1, 0, 0, 0));
}



