/* Copyright (c) 2021 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
/**
* @addtogroup CPmPonResetCfg
* @{
  Class CPmPonResetCfg implements \link IPmPonResetCfg \endlink interface.

  The class ID `PmPonResetCfg` is not included in the default privilege set.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT
#include <stdint.h>
#include "object.h"
#define CPmPonResetCfg_UID UINT32_C(350)
