/* Copyright (c) 2021 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */
/** @file IPmPonResetCfg.idl */
/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT
#include <stdint.h>
#include "object.h"
#define IPmPonResetCfg_ERROR_INVALID_PARAM INT32_C(10)
#define IPmPonResetCfg_ERROR_WARM_RESET_NOT_ALLOWED INT32_C(11)
#define IPmPonResetCfg_OP_ponResetCfg 0
static inline int32_t
IPmPonResetCfg_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}
static inline int32_t
IPmPonResetCfg_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}
static inline int32_t
IPmPonResetCfg_ponResetCfg(Object self, int32_t ponResetSource_val, int32_t ponResetTypeCfg_val, uint32_t s1TimerMs_val, uint32_t s2TimerMs_val)
{
  ObjectArg a[1];
  struct {
    int32_t m_ponResetSource;
    int32_t m_ponResetTypeCfg;
    uint32_t m_s1TimerMs;
    uint32_t m_s2TimerMs;
  } i;
  a[0].b = (ObjectBuf) { &i, 16 };
  i.m_ponResetSource = ponResetSource_val;
  i.m_ponResetTypeCfg = ponResetTypeCfg_val;
  i.m_s1TimerMs = s1TimerMs_val;
  i.m_s2TimerMs = s2TimerMs_val;
  return Object_invoke(self, IPmPonResetCfg_OP_ponResetCfg, a, ObjectCounts_pack(1, 0, 0, 0));
}
