// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CTRegisterModule
* @{
  Class CTRegisterModule implements \link ITRegisterModule \endlink interface.

  The class ID `TRegisterModule` is a platform service in Mink daemon.
*/

// This class provides an interface to register Trusted Processes in Mink daemon.
//

const uint32 CTRegisterModule_UID = 326;

/** @} */
