/*===================================================================================
  Copyright (c) 2020, 2022-2023 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
  ===================================================================================*/

/** @cond */
interface ISecureIndicator {
/** @endcond */

    /**
     @addtogroup ISecureIndicator
     @{
    */

    /** @cond */

    /* ISecureIndicator Error Codes */
    error ERROR_INVALID_PARAM;
    error ERROR_PROVISION;
    error ERROR_STORE;
    error ERROR_LOAD;

    /** @endcond */

    /** @cond */

    /**
      Confirm whether global secure indicator is provisioned

      @param[out]   isProvisioned    Indicator image

      @detdesc
      This method checks whether global secure Indicator is provisioned.
      If the indicator is provisioned, isProvisioned flag is set to 1,
      0 otherwise.

      @return
      Object_OK if successful.
    */
    method isIndicatorProvisioned(out uint32 isProvisioned);

    /**
      Get maximum resolution of the indicator

      @param[out]  maxWidth   Maximum allowed image width
      @param[out]  maxHeight  Maximum allowed image height

      @detdesc
      This method returns maximum allowed width and height of the indicator
      that can be provisioned.

      @return
      Object_OK if successful.
    */
    method getMaxIndicatorResolution(out uint32 maxWidth, out uint32 maxHeight);

    /**
      Set maximum resolution of the indicator

      @param[in]  maxWidth   Maximum allowed image width
      @param[in]  maxHeight  Maximum allowed image height

      @detdesc
      This method set maximum allowed width and height of the indicator
      that can be provisioned.

      @return
      Object_OK if successful.
    */
    method setMaxIndicatorResolution(in uint32 maxWidth, in uint32 maxHeight);

    /**
      Store a new Secure Indicator image

      @param[in]   indicator    Indicator image

      @detdesc
      This method allowes storing a new indicator image in SFS. It also validates the
      image to be png format before storing.

      @return
      Object_OK if successful.
    */
    method storeIndicator(in buffer indicator);

    /**
      Fetch the secure indicator image.

      @param[out]   indicator    Secure Indicator image

      @detdesc
      This method allows client TA to request for global secure indicator image.

      @return
      Object_OK if successful.
    */
    method getIndicator(out buffer indicator);

    /**
      To remove any stored Secure Indicator

      @detdesc
      This method removes already stored secure indicator from SFS.

      @return
      Object_OK if successful.
    */
    method removeIndicator();
    /** @} */ /* end_addtogroup ISecureIndicator */
};
