
help:
	echo type "make test" or "make clean"

test:
	./mpgen

clean:
	rm -f *.pyc jinja2/*.pyc markupsafe/*.pyc
	rm -f defconfig_output.xml
	rm -f kernel_image
	rm -f symbols_tmp.txt
	rm -f headers_tmp.txt
	rm -f rtic_mp.c
	rm -f rtic_mp.h
	rm -f *.py~
	rm -f rtic_mp.xml
	rm -f templates/*~
	rm -f *~
	rm -f ../qrks_mp.bin ../archinfo_tmp.txt  ../headers_tmp.txt  ../kernel_image  ../rtic_mp.c  ../symbols_tmp.txt ../qrks_mp_hex_edited.txt
