VENDOR_SNAPSHOT_MODULES += \
  android.automotive.watchdog-V2-ndk \
  android.frameworks.sensorservice-V1-ndk \
  android.frameworks.sensorservice@1.0 \
  android.hardware.audio.common-V1-ndk \
  android.hardware.audio.common-util \
  android.hardware.audio.common@2.0-util \
  android.hardware.audio.common@4.0 \
  android.hardware.audio.common@4.0-util \
  android.hardware.audio.common@5.0 \
  android.hardware.audio.common@5.0-util \
  android.hardware.audio.common@6.0 \
  android.hardware.audio.common@6.0-util \
  android.hardware.audio.common@7.0 \
  android.hardware.audio.common@7.0-enums \
  android.hardware.audio.common@7.0-util \
  android.hardware.audio.common@7.1-enums \
  android.hardware.audio.common@7.1-util \
  android.hardware.audio.effect@2.0 \
  android.hardware.audio.effect@2.0-impl \
  android.hardware.audio.effect@2.0-util \
  android.hardware.audio.effect@4.0 \
  android.hardware.audio.effect@4.0-impl \
  android.hardware.audio.effect@4.0-util \
  android.hardware.audio.effect@5.0 \
  android.hardware.audio.effect@5.0-impl \
  android.hardware.audio.effect@5.0-util \
  android.hardware.audio.effect@6.0 \
  android.hardware.audio.effect@6.0-impl \
  android.hardware.audio.effect@6.0-util \
  android.hardware.audio.effect@7.0 \
  android.hardware.audio.effect@7.0-impl \
  android.hardware.audio.effect@7.0-util \
  android.hardware.audio.service_64 \
  android.hardware.audio@2.0 \
  android.hardware.audio@2.0-impl \
  android.hardware.audio@2.0-util \
  android.hardware.audio@4.0 \
  android.hardware.audio@4.0-impl \
  android.hardware.audio@4.0-util \
  android.hardware.audio@5.0 \
  android.hardware.audio@5.0-impl \
  android.hardware.audio@5.0-util \
  android.hardware.audio@6.0 \
  android.hardware.audio@6.0-impl \
  android.hardware.audio@6.0-util \
  android.hardware.audio@7.0 \
  android.hardware.audio@7.0-impl \
  android.hardware.audio@7.0-util \
  android.hardware.audio@7.1 \
  android.hardware.audio@7.1-impl \
  android.hardware.audio@7.1-util \
  android.hardware.authsecret@1.0 \
  android.hardware.automotive.vehicle@2.0 \
  android.hardware.automotive.vehicle@2.0-manager-lib \
  android.hardware.biometrics.common-V3-ndk \
  android.hardware.biometrics.common.util \
  android.hardware.biometrics.face-V3-ndk \
  android.hardware.biometrics.fingerprint-V3-ndk \
  android.hardware.bluetooth.audio-V3-ndk \
  android.hardware.bluetooth.audio-impl \
  android.hardware.bluetooth.audio@2.0 \
  android.hardware.bluetooth.audio@2.0-impl \
  android.hardware.bluetooth.audio@2.1 \
  android.hardware.bluetooth@1.0 \
  android.hardware.bluetooth@1.1 \
  android.hardware.boot-V1-ndk \
  android.hardware.boot@1.0 \
  android.hardware.boot@1.1 \
  android.hardware.camera.common-V1-ndk \
  android.hardware.camera.common@1.0-helper \
  android.hardware.camera.device-V1-ndk \
  android.hardware.camera.device-V2-ndk \
  android.hardware.camera.metadata-V1-ndk \
  android.hardware.camera.metadata-V2-ndk \
  android.hardware.camera.provider-V1-ndk \
  android.hardware.camera.provider-V2-ndk \
  android.hardware.cas-V1-ndk \
  android.hardware.cas-service.example \
  android.hardware.cas-service.example-lazy \
  android.hardware.common-V2-ndk \
  android.hardware.drm-V1-ndk \
  android.hardware.drm-service-lazy.clearkey \
  android.hardware.drm-service.clearkey \
  android.hardware.dumpstate-V1-ndk \
  android.hardware.gatekeeper-V1-ndk \
  android.hardware.gatekeeper@1.0 \
  android.hardware.gnss-V3-ndk \
  android.hardware.graphics.allocator-V1-ndk \
  android.hardware.graphics.composer3-V2-ndk \
  android.hardware.graphics.composer@2.1 \
  android.hardware.graphics.composer@2.2 \
  android.hardware.graphics.composer@2.3 \
  android.hardware.health-V1-ndk \
  android.hardware.health-V2-ndk \
  android.hardware.health-translate-ndk \
  android.hardware.health@1.0 \
  android.hardware.health@2.0 \
  android.hardware.health@2.1 \
  android.hardware.identity-V5-ndk \
  android.hardware.keymaster-V3-ndk \
  android.hardware.keymaster-V4-ndk \
  android.hardware.keymaster@3.0 \
  android.hardware.keymaster@4.0 \
  android.hardware.keymaster@4.1 \
  android.hardware.light-V2-ndk \
  android.hardware.media.bufferpool2-V1-ndk \
  android.hardware.media.c2@1.0 \
  android.hardware.media.c2@1.1 \
  android.hardware.media.c2@1.2 \
  android.hardware.nfc-V1-ndk \
  android.hardware.nfc@1.0 \
  android.hardware.nfc@1.1 \
  android.hardware.nfc@1.2 \
  android.hardware.power-V4-ndk \
  android.hardware.power@1.0 \
  android.hardware.power@1.1 \
  android.hardware.power@1.2 \
  android.hardware.radio-V2-ndk \
  android.hardware.radio.config-V2-ndk \
  android.hardware.radio.data-V2-ndk \
  android.hardware.radio.messaging-V2-ndk \
  android.hardware.radio.modem-V2-ndk \
  android.hardware.radio.network-V2-ndk \
  android.hardware.radio.sap-V1-ndk \
  android.hardware.radio.sim-V2-ndk \
  android.hardware.radio.voice-V2-ndk \
  android.hardware.radio@1.0 \
  android.hardware.radio@1.1 \
  android.hardware.radio@1.2 \
  android.hardware.radio@1.3 \
  android.hardware.radio@1.4 \
  android.hardware.radio@1.5 \
  android.hardware.radio@1.6 \
  android.hardware.renderscript@1.0-impl \
  android.hardware.secure_element-V1-ndk \
  android.hardware.secure_element@1.0 \
  android.hardware.security.keymint-V1-ndk \
  android.hardware.security.keymint-V2-ndk \
  android.hardware.security.keymint-V3-ndk \
  android.hardware.security.rkp-V3-ndk \
  android.hardware.security.secureclock-V1-ndk \
  android.hardware.security.sharedsecret-V1-ndk \
  android.hardware.security.sharedsecret-V2-ndk \
  android.hardware.sensors-V2-ndk \
  android.hardware.sensors-service.multihal \
  android.hardware.sensors@1.0 \
  android.hardware.sensors@2.0 \
  android.hardware.sensors@2.0-ScopedWakelock \
  android.hardware.sensors@2.1 \
  android.hardware.soundtrigger@2.1 \
  android.hardware.soundtrigger@2.2 \
  android.hardware.soundtrigger@2.2-impl \
  android.hardware.soundtrigger@2.3 \
  android.hardware.soundtrigger@2.3-impl \
  android.hardware.tetheroffload-V1-ndk \
  android.hardware.thermal-V1-ndk \
  android.hardware.thermal@1.0 \
  android.hardware.thermal@2.0 \
  android.hardware.usb-V1-ndk \
  android.hardware.usb.gadget-V1-ndk \
  android.hardware.usb.gadget@1.0 \
  android.hardware.usb.gadget@1.1 \
  android.hardware.vibrator-V2-ndk \
  android.hardware.weaver-V2-ndk \
  android.hardware.wifi.hostapd-V1-ndk \
  android.hardware.wifi.supplicant-V1-ndk \
  android.hardware.wifi.supplicant-V2-ndk \
  android.hardware.wifi@1.0 \
  android.hardware.wifi@1.1 \
  android.hardware.wifi@1.2 \
  android.hardware.wifi@1.3 \
  android.hardware.wifi@1.4 \
  android.hidl.allocator@1.0 \
  android.hidl.memory.block@1.0 \
  android.media.audio.common.types-V2-ndk \
  android.system.keystore2-V1-ndk \
  android.system.net.netd-V1-ndk \
  android.system.wifi.keystore@1.0 \
  audio.bluetooth.default \
  audio.primary.default \
  audio.r_submix.default \
  audio.usb.default \
  awk_vendor \
  boringssl_self_test_vendor \
  com.dsi.ant@1.0 \
  crtbegin_dynamic \
  crtbegin_so \
  crtend_android \
  crtend_so \
  dmabuf_dump \
  dumpsys_vendor \
  gpu_counter_producer \
  libFraunhoferAAC \
  libaidlcommonsupport \
  libalsautils \
  libandroid_runtime_lazy \
  libarect \
  libasync_safe \
  libaudiopreprocessing \
  libavservices_minijail \
  libbase \
  libbatterymonitor \
  libbinderdebug \
  libbluetooth_audio_session \
  libbluetooth_audio_session_aidl \
  libboot_control \
  libbootloader_message \
  libbootloader_message_vendor \
  libbundlewrapper \
  libc++_static \
  libc++demangle \
  libcamera2ndk_vendor \
  libclang_rt.builtins \
  libclang_rt.ubsan_minimal \
  libclearkeycasplugin \
  libcodec2_hidl@1.0 \
  libcodec2_hidl@1.1 \
  libcodec2_hidl@1.2 \
  libcodec2_hidl_plugin \
  libcodec2_vndk \
  libcutils \
  libdownmix \
  libdrm \
  libdrmclearkeyplugin \
  libdynproc \
  libedify \
  libeffectproxy \
  libeffects \
  libeffectsconfig \
  libfstab \
  libgmock \
  libgrallocusage \
  libgtest \
  libgtest_main \
  libhapticgenerator \
  libhealth_aidl_impl \
  libhealthd_charger_ui \
  libhealthd_draw \
  libhealthhalutils \
  libhealthloop \
  libhidltransport \
  libhidparser \
  libhwbinder \
  libjsmn \
  libjsoncpp \
  libkeymaster_messages \
  libkeystore-engine-wifi-hidl \
  libkeystore-wifi-hidl \
  libldnhncr \
  libmediautils_vendor \
  libmemunreachable \
  libminui \
  libnbaio_mono \
  libnetfilter_conntrack \
  libnfnetlink \
  libotautil \
  libpcap \
  libprotobuf-c-nano-enable_malloc \
  libprotobuf-c-nano-enable_malloc-32bit \
  libprotobuf-cpp-full \
  libprotobuf-cpp-lite \
  libpsi \
  libreverbwrapper \
  librilutils \
  libsensorndkbridge \
  libsgutils2 \
  libstagefright_aidl_bufferpool2 \
  libstagefright_bufferpool@2.0.1 \
  libsuspend \
  libusbconfigfs \
  libutils \
  libvibratorutils \
  libvisualizer \
  local_time.default \
  logwrapper_vendor \
  note_memtag_heap_sync \
  power.default \
  sensors.dynamic_sensor_hal \
  sg_write_buffer \
  sh_vendor \
  toolbox_vendor \
  toybox_vendor \
  vibrator.default \
  vndservice \
  vndservicemanager \
