/*===================================================================================
    Copyright (c) 2020-2021 Qualcomm Technologies, Inc.
    All Rights Reserved.
    Confidential and Proprietary - Qualcomm Technologies, Inc.
 ===================================================================================*/
/**
* @addtogroup CCPZLicense
* @{
  Class CCPZLicense implements \link ICPZLicense \endlink interface.

  This service is expected to be called from non-secure clients and not
  necessarily from TAs.
  Any DRM implmentation should call this service from HLOS prior to
  starting a DRM session.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CCPZLicense_UID UINT32_C(811)
