// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
* @addtogroup CDiagFuseService
* @{
  Class CDiagFuseService implements \link IDiagFuseService \endlink interface.

*/
// This class provides an interface to access legacy QSEECOM services via SMCI.
//
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CDiagFuseService_UID UINT32_C(265)


