#pragma once
// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CDiagFuseService
* @{
  Class CDiagFuseService implements \link IDiagFuseService \endlink interface.

*/

// This class provides an interface to access legacy QSEECOM services via SMCI.

//

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

static const uint32_t CDiagFuseService_UID = UINT32_C(265);


