// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
* @addtogroup CGPAppClient
* @{
  Class CGPAppClient implements \link IGPAppClient \endlink interface.
  This service is exposed to HLOS client.
  This class should be used only by our GP stack, not by individual clients.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CGPAppClient_UID UINT32_C(0x199)

