#pragma once
// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CGPAppClient
* @{
  Class CGPAppClient implements \link IGPAppClient \endlink interface.
  This service is exposed to HLOS client.
  This class should be used only by our GP stack, not by individual clients.
*/

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

static const uint32_t CGPAppClient_UID = UINT32_C(0x199);

