// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
 * @addtogroup CPeripheralAccessControl
 * @{
  Class CPeripheralAccessControl implements \link IPeripheralAccessControl \endlink interface.
  This class provides interface to enable or disable each peripheral dynamically.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CPeripheralAccessControl_AUDIO_UID UINT32_C(0x501)

#define CPeripheralAccessControl_BLUETOOTH_UID UINT32_C(0x502)

#define CPeripheralAccessControl_CAMERA_UID UINT32_C(0x503)

#define CPeripheralAccessControl_MODEM_UID UINT32_C(0x504)

#define CPeripheralAccessControl_GNSS_UID UINT32_C(0x505)

#define CPeripheralAccessControl_NFC_UID UINT32_C(0x506)

#define CPeripheralAccessControl_USB_UID UINT32_C(0x507)

#define CPeripheralAccessControl_WIFI_UID UINT32_C(0x508)


