// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
 * @addtogroup CPeripheralState
 * @{
  Class CPeripheralState implements \link IPeripheralState \endlink interface.
  This class provides interface to get notification and state about mode of peripherals registered.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CPeripheralState_UID UINT32_C(0x108)


