#pragma once
/*
 * Copyright (c) 2021-2022 Qualcomm Technologies, Inc.
 * All Rights Reserved.
 * Confidential and Proprietary - Qualcomm Technologies, Inc.
 */

/**
* @addtogroup CQWESTAServices
* @{
  Class CQWESTAServices implements \link IQWESTAServices \endlink interface.

  The class ID `QWESTAServices` is not included in the default privilege set.
  It needs to be added to the privileges section in the metadata to allow the
  TA to use the CQWESTAServices class.
*/

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

static const uint32_t CQWESTAServices_UID = UINT32_C(120);


