#pragma once
// Copyright (c) 2022 Qualcomm Technologies, Inc. 
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CRegisterListenerCBO
* @{
  Class CRegisterListenerCBO implements \link IRegisterListenerCBO \endlink interface.

  The class ID `RegisterListenerCBO` is not included in the default privilege set. It needs to be added to the
  privileges section in the metadata to allow the TA to use the CRegisterListenerCBO class.
*/

// AUTOGENERATED FILE: DO NOT EDIT

#include <cstdint>
#include "object.h"
#include "proxy_base.hpp"

static const uint32_t CRegisterListenerCBO_UID = UINT32_C(87);
