// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
* @addtogroup CRegisterListenerCBO
* @{
  Class CRegisterListenerCBO implements \link IRegisterListenerCBO \endlink interface.

  The class ID `RegisterListenerCBO` is not included in the default privilege set. It needs to be added to the
  privileges section in the metadata to allow the TA to use the CRegisterListenerCBO class.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CRegisterListenerCBO_UID UINT32_C(87)
