// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.

/**
* @addtogroup CTProcessLoader
* @{
  Class CTProcessLoader implements \link ITProcessLoader \endlink interface.

  The class ID `TProcessLoader` is a platform service in Mink daemon.
*/
// This class provides an interface to load Trusted Processes in Mink daemon.
//
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CTProcessLoader_UID UINT32_C(324)


