/*
* Copyright (c) 2018 - 2023 Qualcomm Technologies, Inc.
* All Rights Reserved.
* Confidential and Proprietary - Qualcomm Technologies, Inc.
*/
// This is an auto-generated file from input/cmdGetCTLTPCFTMDataStandalone.s
#include "tlv2Inc.h"
#include "cmdGetCTLTPCFTMDataStandalone.h"

void* initGETCTLTPCFTMDATASTANDALONEOpParms(A_UINT8 *pParmsCommon, PARM_OFFSET_TBL *pParmsOffset, PARM_DICT *pParmDict)
{
    int i, j; 	//for initializing array parameter
    CMD_GETCTLTPCFTMDATASTANDALONE_PARMS  *pGETCTLTPCFTMDATASTANDALONEParms = (CMD_GETCTLTPCFTMDATASTANDALONE_PARMS *)pParmsCommon;

    if (pParmsCommon == NULL) return (NULL);

    i = j = 0;	//assign a number to avoid warning in case i and j are not used

    // Populate the parm structure with initial values
    pGETCTLTPCFTMDATASTANDALONEParms->ctlRd = pParmDict[PARM_CTLRD].v.valU8;
    pGETCTLTPCFTMDATASTANDALONEParms->ctlGroup = pParmDict[PARM_CTLGROUP].v.valU8;
    pGETCTLTPCFTMDATASTANDALONEParms->ctlVerbose = pParmDict[PARM_CTLVERBOSE].v.valU8;
    pGETCTLTPCFTMDATASTANDALONEParms->ctlNonOfdmaType = pParmDict[PARM_CTLNONOFDMATYPE].v.valU8;
    pGETCTLTPCFTMDATASTANDALONEParms->freq = pParmDict[PARM_FREQ].v.valU16;
    pGETCTLTPCFTMDATASTANDALONEParms->rateBitIndex = pParmDict[PARM_RATEBITINDEX].v.valU16;
    pGETCTLTPCFTMDATASTANDALONEParms->nss = pParmDict[PARM_NSS].v.valU32;
    pGETCTLTPCFTMDATASTANDALONEParms->ctlEbw = pParmDict[PARM_CTLEBW].v.valU16;
    pGETCTLTPCFTMDATASTANDALONEParms->beamForming = pParmDict[PARM_BEAMFORMING].v.valU8;
    pGETCTLTPCFTMDATASTANDALONEParms->numChain = pParmDict[PARM_NUMCHAIN].v.valU8;
    pGETCTLTPCFTMDATASTANDALONEParms->ctlExceptionValue = pParmDict[PARM_CTLEXCEPTIONVALUE].v.valS8;

    // Make up ParmOffsetTbl
    resetParmOffsetFields();
    fillParmOffsetTbl((A_UINT32)PARM_CTLRD, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->ctlRd)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_CTLGROUP, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->ctlGroup)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_CTLVERBOSE, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->ctlVerbose)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_CTLNONOFDMATYPE, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->ctlNonOfdmaType)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_FREQ, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->freq)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_RATEBITINDEX, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->rateBitIndex)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_NSS, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->nss)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_CTLEBW, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->ctlEbw)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_BEAMFORMING, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->beamForming)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_NUMCHAIN, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->numChain)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_CTLEXCEPTIONVALUE, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONEParms->ctlExceptionValue)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONEParms), pParmsOffset);
    return((void*) pGETCTLTPCFTMDATASTANDALONEParms);
}

static GETCTLTPCFTMDATASTANDALONE_OP_FUNC GETCTLTPCFTMDATASTANDALONEOpFunc = NULL;

TLV2_API void registerGETCTLTPCFTMDATASTANDALONEHandler(GETCTLTPCFTMDATASTANDALONE_OP_FUNC fp)
{
    GETCTLTPCFTMDATASTANDALONEOpFunc = fp;
}

A_BOOL GETCTLTPCFTMDATASTANDALONEOp(void *pParms)
{
    CMD_GETCTLTPCFTMDATASTANDALONE_PARMS *pGETCTLTPCFTMDATASTANDALONEParms = (CMD_GETCTLTPCFTMDATASTANDALONE_PARMS *)pParms;

#if 0 //for debugging, comment out this line, and uncomment the line below
//#ifdef _DEBUG
    int i; 	//for initializing array parameter
    i = 0;	//assign a number to avoid warning in case i is not used

    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: ctlRd %u\n", pGETCTLTPCFTMDATASTANDALONEParms->ctlRd);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: ctlGroup %u\n", pGETCTLTPCFTMDATASTANDALONEParms->ctlGroup);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: ctlVerbose %u\n", pGETCTLTPCFTMDATASTANDALONEParms->ctlVerbose);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: ctlNonOfdmaType %u\n", pGETCTLTPCFTMDATASTANDALONEParms->ctlNonOfdmaType);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: freq %u\n", pGETCTLTPCFTMDATASTANDALONEParms->freq);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: rateBitIndex %u\n", pGETCTLTPCFTMDATASTANDALONEParms->rateBitIndex);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: nss %u\n", pGETCTLTPCFTMDATASTANDALONEParms->nss);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: ctlEbw %u\n", pGETCTLTPCFTMDATASTANDALONEParms->ctlEbw);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: beamForming %u\n", pGETCTLTPCFTMDATASTANDALONEParms->beamForming);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: numChain %u\n", pGETCTLTPCFTMDATASTANDALONEParms->numChain);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONEOp: ctlExceptionValue %u\n", pGETCTLTPCFTMDATASTANDALONEParms->ctlExceptionValue);
#endif //_DEBUG

    if (NULL != GETCTLTPCFTMDATASTANDALONEOpFunc) {
        (*GETCTLTPCFTMDATASTANDALONEOpFunc)(pGETCTLTPCFTMDATASTANDALONEParms);
    }
    return(TRUE);
}

void* initGETCTLTPCFTMDATASTANDALONERSPOpParms(A_UINT8 *pParmsCommon, PARM_OFFSET_TBL *pParmsOffset, PARM_DICT *pParmDict)
{
    int i, j; 	//for initializing array parameter
    CMD_GETCTLTPCFTMDATASTANDALONERSP_PARMS  *pGETCTLTPCFTMDATASTANDALONERSPParms = (CMD_GETCTLTPCFTMDATASTANDALONERSP_PARMS *)pParmsCommon;

    if (pParmsCommon == NULL) return (NULL);

    i = j = 0;	//assign a number to avoid warning in case i and j are not used

    // Populate the parm structure with initial values
    pGETCTLTPCFTMDATASTANDALONERSPParms->status = pParmDict[PARM_STATUS].v.valU8;
    memset(pGETCTLTPCFTMDATASTANDALONERSPParms->pad3, 0, sizeof(pGETCTLTPCFTMDATASTANDALONERSPParms->pad3));
    pGETCTLTPCFTMDATASTANDALONERSPParms->numRows = pParmDict[PARM_NUMROWS].v.valU32;
    pGETCTLTPCFTMDATASTANDALONERSPParms->eachRowSize = pParmDict[PARM_EACHROWSIZE].v.valU32;
    memset(pGETCTLTPCFTMDATASTANDALONERSPParms->ctlRowData, 0, sizeof(pGETCTLTPCFTMDATASTANDALONERSPParms->ctlRowData));

    // Make up ParmOffsetTbl
    resetParmOffsetFields();
    fillParmOffsetTbl((A_UINT32)PARM_STATUS, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONERSPParms->status)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONERSPParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_PAD3, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONERSPParms->pad3)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONERSPParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_NUMROWS, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONERSPParms->numRows)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONERSPParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_EACHROWSIZE, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONERSPParms->eachRowSize)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONERSPParms), pParmsOffset);
    fillParmOffsetTbl((A_UINT32)PARM_CTLROWDATA, (A_UINT32)(((A_UINT32)&(pGETCTLTPCFTMDATASTANDALONERSPParms->ctlRowData)) - (A_UINT32)pGETCTLTPCFTMDATASTANDALONERSPParms), pParmsOffset);
    return((void*) pGETCTLTPCFTMDATASTANDALONERSPParms);
}

static GETCTLTPCFTMDATASTANDALONERSP_OP_FUNC GETCTLTPCFTMDATASTANDALONERSPOpFunc = NULL;

TLV2_API void registerGETCTLTPCFTMDATASTANDALONERSPHandler(GETCTLTPCFTMDATASTANDALONERSP_OP_FUNC fp)
{
    GETCTLTPCFTMDATASTANDALONERSPOpFunc = fp;
}

A_BOOL GETCTLTPCFTMDATASTANDALONERSPOp(void *pParms)
{
    CMD_GETCTLTPCFTMDATASTANDALONERSP_PARMS *pGETCTLTPCFTMDATASTANDALONERSPParms = (CMD_GETCTLTPCFTMDATASTANDALONERSP_PARMS *)pParms;

#if 0 //for debugging, comment out this line, and uncomment the line below
//#ifdef _DEBUG
    int i; 	//for initializing array parameter
    i = 0;	//assign a number to avoid warning in case i is not used

    A_PRINTF("GETCTLTPCFTMDATASTANDALONERSPOp: status %u\n", pGETCTLTPCFTMDATASTANDALONERSPParms->status);
    for (i = 0; i < 3 ; i++)
    {
        A_PRINTF("GETCTLTPCFTMDATASTANDALONERSPOp: pad3 %u\n", pGETCTLTPCFTMDATASTANDALONERSPParms->pad3[i]);
    }
    A_PRINTF("GETCTLTPCFTMDATASTANDALONERSPOp: numRows %u\n", pGETCTLTPCFTMDATASTANDALONERSPParms->numRows);
    A_PRINTF("GETCTLTPCFTMDATASTANDALONERSPOp: eachRowSize %u\n", pGETCTLTPCFTMDATASTANDALONERSPParms->eachRowSize);
    for (i = 0; i < 8 ; i++) // can be modified to print up to 512 entries
    {
        A_PRINTF("GETCTLTPCFTMDATASTANDALONERSPOp: ctlRowData %u\n", pGETCTLTPCFTMDATASTANDALONERSPParms->ctlRowData[i]);
    }
#endif //_DEBUG

    if (NULL != GETCTLTPCFTMDATASTANDALONERSPOpFunc) {
        (*GETCTLTPCFTMDATASTANDALONERSPOpFunc)(pGETCTLTPCFTMDATASTANDALONERSPParms);
    }
    return(TRUE);
}
